# Why VR + R


## Questions

* What are our motivations for learning about how to use Virtual Reality with R?
* What are the use cases for VR + R?

## Overview

* Teaching: 2 min
* Exercises: 5 min

## Why are we here? {.exercise}

Form groups of up to four people with your neighbours and discuss your interest in VR and R.


Consider:

* What kind of data do you have that you would like to explore in VR?
* What are the best VR experiences you have had?
* Who would you be creating VR experiences for?

## R + VR for Science

The motivation for this work with R and VR is to give people who analyse data in R, like
scientists, the opportunity to use that data in a virtual reality experience
without having to engage with specialist 3D software developers.

At ACEMS we have been investigating VR as tool for communicating science
relating to the Great Barrier Reef and also eliciting expert information for
spatial models.

Within the context of the spatial work we found that WebVR was particularly nice
as a platform for visualising spatial data, since WebVR scenes:

* are easy to distribute online and require no special software or hardware to view, although the viewing is enhanced by VR hardware.
* give the user complete control of the camera
* have convenient API for scripting user interactions.

## This Workshop:

The workshop is split into three rough acts:

1. Intro to WebVR and A-Frame in HTML, on glitch.com
2. General 3D representations of spatial data in R
3. Creating WebVR scenes in R using spatial data.
